//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDevx
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loanDetail()
        {
            this.products = new HashSet<product>();
        }
    
        public int loanID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> loanByID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<System.DateTime> loanDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
        public virtual user user { get; set; }
    }
}
