//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDevx
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public string productFeatures { get; set; }
        public Nullable<int> purchaseID { get; set; }
        public Nullable<byte> isAvailable { get; set; }
        public Nullable<int> loanID { get; set; }
        public Nullable<int> pieces { get; set; }
    
        public virtual loanDetail loanDetail { get; set; }
        public virtual purchase purchase { get; set; }
    }
}
