//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDevx.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanDetail
    {
        public int loanID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> loanByID { get; set; }
        public Nullable<int> productID { get; set; }
        public string loanDate { get; set; }
        public Nullable<int> loanPieces { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
