//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDevx.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.loanDetails = new HashSet<loanDetail>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        public string productFeatures { get; set; }
        public Nullable<int> purchaseID { get; set; }
        public Nullable<byte> isAvailable { get; set; }
        public Nullable<int> pieces { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loanDetail> loanDetails { get; set; }
        public virtual purchase purchase { get; set; }
    }
}
